#### Note:

Make sure that you have these two scripts running at the same time while running this

ark regsitry start

python sim_node.py

In [75]:
import time
import numpy as np
from arktypes import joint_group_command_t, task_space_command_t, joint_state_t
from arktypes.utils import pack, unpack
from ark.client.comm_infrastructure.instance_node import InstanceNode

ROBOT_NAME = "arkbot" # ArkBot
SIM = False

class HarkControllerNode(InstanceNode):
    def __init__(self):
        super().__init__("arkbot_controller") # ArkBotController
        suffix = "/sim" if SIM else ""
        base = f"{ROBOT_NAME}"

        # pubs
        self.joint_group_command = self.create_publisher(f"{base}/joint_group_command{suffix}", joint_group_command_t)
        self.joint_group_command_real = self.create_publisher(f"{base}/joint_group_command", joint_group_command_t)
        self.task_space_command  = self.create_publisher(f"{base}/cartesian_command{suffix}", task_space_command_t)

        # subs
        self.state = self.create_listener(f"{base}/joint_states{suffix}", joint_state_t)

node = HarkControllerNode()


[WARNING] [18:00:58.334754] - No global configuration provided. Using default system configuration.
[INFO] [18:00:58.337701] - Service: Successfully registered '__DEFAULT_SERVICE/GetInfo/arkbot_controller_c965dca6-4c5d-419e-8b8f-31a048a5ef07' with registry.
[INFO] [18:00:58.339367] - Service: Successfully registered '__DEFAULT_SERVICE/SuspendNode/arkbot_controller_c965dca6-4c5d-419e-8b8f-31a048a5ef07' with registry.
[INFO] [18:00:58.341342] - Service: Successfully registered '__DEFAULT_SERVICE/RestartNode/arkbot_controller_c965dca6-4c5d-419e-8b8f-31a048a5ef07' with registry.
[ERROR] [18:00:58.342158] - Couldn't load config for other 'arkbot_controller'
[OK] [18:00:58.343067] - setup publisher arkbot/joint_group_command[joint_group_command_t]
[OK] [18:00:58.343788] - setup publisher arkbot/joint_group_command[joint_group_command_t]
[OK] [18:00:58.344393] - setup publisher arkbot/cartesian_command[task_space_command_t]
[OK] [18:00:58.345517] - subscribed to arkbot/joint_states[joint_stat

None


---

# Joint Group Control

In [96]:
all_cmd = [
    1.0,   # Revolute 1 (continuous)
     0.0,   # Revolute 2 (rad)
     0.0,   # Revolute 4 (rad)
     0.00,   # Revolute 5 (continuous)
     0.00,   # Revolute 6 (rad)
     0.000   # Slider 7 position in meters (range 0.0 .. 0.0425)
]
node.joint_group_command.publish(pack.joint_group_command(all_cmd, "all"))

In [167]:
home =  [0.0, 0.0, 0.0, 0.00, 0.0, 0.0, 0.0]
approach_upper = [0.4, 0, 1.2, -2.0, 0.0, 2, 0.0]
contact_upper = [0.4, -0.3, 1.3, -2.0, 0.0, 2.2, 0.0]
push_upper = [0.4, -0.3, 1.3, -1.2, 0.0, 1.6, 0.0]
lower_upper = [0.4, -0.3, 1.3, -2.0, 0.0, 2.2, 0.0]
approach_lower = [0.4, -0.3, 1.8, -2.0, 0.0, 2.2, 0.0]
contact_lower = [0.4, -0.4, 1.8, -1.5, 0.0, 2.2, 0.0]
push_lower = [0.4, -0.4, 1.8, -0.5, 0.0, 1.4, 0.0]
retract_lower = [0.4, 0.3, 1.8, -2.0, 0.0, 2.2, 0.0]


In [257]:
node.joint_group_command.publish(pack.joint_group_command(home, "all"))

In [140]:
node.joint_group_command.publish(pack.joint_group_command(approach_upper, "all"))

In [156]:
node.joint_group_command.publish(pack.joint_group_command(contact_upper, "all"))

In [162]:
node.joint_group_command.publish(pack.joint_group_command(push_upper, "all"))

In [163]:
node.joint_group_command.publish(pack.joint_group_command(lower_upper, "all"))

In [164]:
node.joint_group_command.publish(pack.joint_group_command(approach_lower, "all"))

In [168]:
node.joint_group_command.publish(pack.joint_group_command(contact_lower, "all"))

In [169]:
node.joint_group_command.publish(pack.joint_group_command(push_lower, "all"))

In [170]:
node.joint_group_command.publish(pack.joint_group_command(retract_lower, "all"))

In [ ]:
home2 =  [-1.5, 0, 1.2, -2.0, 0.0, 2, 0.0]
first = [-1.2, -0.3, 1.2, -2.0, 0.0, 2, 0.0]
second = [-1.2, -0.5, 2, -1.5, 0.0, 2.2, 0.0]
third = [-1.2, -0.5, 2, -0.8, 0.0, 1.8, 0.0]
fourth = [-1.2, -0.5, 2, -0.8, 0.0, 1.8, 0.15]
fifth = [-1.2, -0.3, 1.8, -1, 0.0, 2.0, 0.15]
sixth = [-1.9, -0.3, 1.8, -1, 0.0, 2.0, 0.15]
seventh = [-1.9, -0.5, 2, -0.8, 0.0, 1.8, 0.15]
eighth = [-1.9, -0.5, 2, -0.8, 0.0, 1.8, 0]


In [ ]:
node.joint_group_command.publish(pack.joint_group_command(eighth, "all"))

In [259]:
node.joint_group_command.publish(pack.joint_group_command(home2, "all"))

In [209]:
node.joint_group_command.publish(pack.joint_group_command(first, "all"))

In [216]:
node.joint_group_command.publish(pack.joint_group_command(second, "all"))

In [238]:
node.joint_group_command.publish(pack.joint_group_command(third, "all"))

In [239]:
node.joint_group_command.publish(pack.joint_group_command(fourth, "all"))

In [ ]:
node.joint_group_command.publish(pack.joint_group_command(fifth, "all"))

In [ ]:
node.joint_group_command.publish(pack.joint_group_command(sixth, "all"))

In [ ]:
node.joint_group_command.publish(pack.joint_group_command(seventh, "all"))

In [ ]:
node.joint_group_command.publish(pack.joint_group_command(eighth, "all"))

In [613]:
# save the position offset, click this once when the robot is in the zero position
# unpack.joint_state(node.state.get())

joint_state_data = unpack.joint_state(node.state.get())

joint_positions = joint_state_data[2]

print(joint_positions)



[ 0.4000281   0.         -1.2000843   2.00031095  0.          2.05553426
  0.        ]


In [7]:
# GRIPPER (velocity mode): single value for Slider 7 velocity (m/s)
gripper_vel_open  = [ +0.010 ]   # open slowly
gripper_vel_close = [ -0.010 ]   # close slowly
node.joint_group_command.publish(pack.joint_group_command(gripper_vel_open, "gripper"))

In [8]:
# ARM (position mode): 6 values, Revolute 1..6
arm_cmd = [-0.30, 0.50, 0.30, -1.00, 0.10, 0.80]
node.joint_group_command.publish(pack.joint_group_command(arm_cmd, "arm"))


---

# Task Space Control

In [7]:
xyz_command = np.array([0.3, 0.4, 0.8])
quaternion_command = np.array([1, 0.0, 0.0, 0.0]) # xyz-w
gripper = 1.0 # 0.0 close, 1.0 open

controller.task_space_command.publish(
    pack.task_space_command("all", xyz_command, quaternion_command, gripper))

---


# Joint States

In [287]:
unpack.joint_state(node.state.get())


({'seq': 0, 'stamp': {'sec': 0, 'nsec': 0}, 'frame_id': ''},
 ['Revolute 1',
  'Revolute 2',
  'Revolute 3',
  'Revolute 4',
  'Revolute 5',
  'Revolute 6',
  'Slider 7'],
 array([0.99998503, 0.99998503, 0.        , 0.        , 0.        ,
        0.        , 0.        ]),
 array([0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0.]))

# PYBULLET TESTING

In [73]:
import pybullet as p, pybullet_data as pd, math

p.connect(p.DIRECT)  # use GUI to debug
p.setGravity(0, 0, -9.81)

robot = p.loadURDF("/home/sarthakdas/Ark/ark_bot/arkbot/ark_bot.urdf", [0, 0, 0], useFixedBase=True)

# print("Joints in robot:")
for j in range(p.getNumJoints(robot)):
    print(j, p.getJointInfo(robot, j)[12].decode())

# # Pick correct end effector index after checking printout
ee = 5

target_pos = [0.0, 0.0, 0.5]
target_orn = p.getQuaternionFromEuler([0.0, 0.0, 0.0])

q = p.calculateInverseKinematics(robot, ee, target_pos, target_orn)

print("IK solution:", q[:p.getNumJoints(robot)])

node.joint_group_command.publish(pack.joint_group_command(q, "all"))
node.joint_group_command_real.publish(pack.joint_group_command(q, "all"))

p.disconnect()


0 Link1
1 link2
2 link3
3 link4
4 link5
5 Hand
6 finger1
7 finger2
IK solution: (-1.0618388096278041e-05, 0.0002203514868508854, 0.0007021935362270586, -1.0795412669870966e-05, 1.2113377418749757e-05, 0.0004775087422464768, 0.0, 0.0)
